---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${aistor_pv_name}
spec:
  capacity:
    storage: ${aistor_pv_size}Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ${storage_class_name}
  local:
    path: ${aistor_data_dir}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          %{ for hostname in hostnames ~}
            - "${hostname}"
          %{ endfor ~}
