name: MinIO Deployment

on:
  push:
    branches:
      - main

env:
  destroy: true

jobs:
  set-condition:
    runs-on: ubuntu-latest
    outputs:
      run-job: ${{ steps.set-output.outputs.RUN_JOB }}
    steps:
      - name: Set condition
        id: set-output
        run: |
          echo "RUN_JOB=${{ env.destroy }}" >> $GITHUB_OUTPUT
  aws-build:
    needs: set-condition
    if: needs.set-condition.outputs.run-job == 'false'
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: "us-west-2"
      TF_S3_BUCKET: "minio-terraform-state112024"
      TF_S3_KEY: "terraform.tfstate"
      TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/terraform/.plugin-cache
      TF_K8S_WORKSPACE: k8s
    steps:
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION

      - name: Check if S3 Bucket Exists
        id: check-bucket
        run: |
          if aws s3api head-bucket --bucket $TF_S3_BUCKET 2>/dev/null; then
            echo "bucket_exists=true" >> $GITHUB_ENV
          else
            echo "bucket_exists=false" >> $GITHUB_ENV
          fi
    
      - name: Create AWS S3 bucket
        if: env.bucket_exists == 'false'
        run: |
          aws s3api create-bucket --bucket $TF_S3_BUCKET --region $AWS_DEFAULT_REGION --create-bucket-configuration LocationConstraint=$AWS_DEFAULT_REGION
          aws s3api put-object --bucket $TF_S3_BUCKET --key $TF_S3_KEY

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main #<- Define the branch you wish to use!

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Create Plugin Cache Dir
        run: mkdir ${{ env.TF_PLUGIN_CACHE_DIR }}

      - name: Initialize K8S-Cluster Terraform
        working-directory: ./terraform/k8s-cluster
        run: export TF_PLUGIN_CACHE_DIR=${{ env.TF_PLUGIN_CACHE_DIR }}; terraform init -backend-config="bucket=${TF_S3_BUCKET}" -backend-config="key=${TF_S3_KEY}" -backend-config="region=${AWS_DEFAULT_REGION}"

      - name: Determine K8S-Cluster Terraform Workspace
        working-directory: ./terraform/k8s-cluster
        run: |
          if terraform workspace select ${{ env.TF_K8S_WORKSPACE }} 2>/dev/null; then
            echo "Workspace ${{ env.TF_K8S_WORKSPACE }} Selected!"
          else
            terraform workspace new ${{ env.TF_K8S_WORKSPACE }}
          fi

      - name: Apply New Terraform
        working-directory: ./terraform/k8s-cluster
        run: terraform apply -auto-approve -var="sshkey=$(echo "${{ secrets.SSHKEY }}" | base64 --decode)"

  ansible-build:
      needs: [set-condition, aws-build]
      if: needs.set-condition.outputs.run-job == 'false'
      runs-on: ubuntu-latest
      env:
        AWS_DEFAULT_REGION: "us-west-2"
        INI_FILE: "/home/runner/project.ini"
        KEY_FILE: "/home/runner/sre-key"
        NODES_FILE: "/home/runner/nodes.json"
        ANSIBLE_USER: "ubuntu"
        K8S_CONF_FILE: "/tmp/config"
      steps:
        - name: Configure AWS credentials
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_DEFAULT_REGION
        
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            ref: main #<- Define the branch you wish to use.

        - name: Decode SSH key
          run: |
            base64 -d <<< '${{ secrets.PRIVATE_SSHKEY }}' > ${{ env.KEY_FILE }}
            chmod 0600 ${{ env.KEY_FILE }}

        - name: Validate SSH Key
          run: ssh-keygen -l -f ${{ env.KEY_FILE }}

        - name: Update project.ini File
          working-directory: ./ansible
          run: bash -x update-ini.sh ${{ env.ANSIBLE_USER }} ${{ env.KEY_FILE }} ${{ env.INI_FILE }} ${{ env.NODES_FILE }}

        - name: Check project.ini File
          run: cat ${{ env.INI_FILE }}

        - name: Read Inventory File
          id: read-inventory
          run: |
            echo "inventory_content<<EOF" >> $GITHUB_ENV
            cat ${{ env.INI_FILE }} >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV

        - name: Clone Ansible Role
          working-directory: ./ansible
          run: git clone https://github.com/excircle/ansible-cncf-k8s-role roles/ansible-cncf-k8s-role

        - name: Run Ansible Playbook
          uses: dawidd6/action-ansible-playbook@v2
          with:
            playbook: k8s-bootstrap.yaml
            directory: ./ansible
            inventory: ${{ env.inventory_content }}
            options: |
              --extra-vars="local_kube_config=/tmp/config"

        - name: Upload K8S Config File
          uses: actions/upload-artifact@v3
          with:
            name: config
            path: /tmp/config

  aistor-deploy:
    needs: [set-condition, aws-build]
    if: needs.set-condition.outputs.run-job == 'false'
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: "us-west-2"
    steps:
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION
      - name: 

  destroy:
    needs: set-condition
    if: needs.set-condition.outputs.run-job == 'true'
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: "us-west-2"
      TF_S3_BUCKET: "minio-terraform-state112024"
      TF_S3_KEY: "terraform.tfstate"
      TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/terraform/.plugin-cache
      TF_K8S_WORKSPACE: k8s
    steps:
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main #<- Define the branch you wish to use.

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        working-directory: ./terraform/k8s-cluster
        run: export TF_PLUGIN_CACHE_DIR=${{ env.TF_PLUGIN_CACHE_DIR }}; terraform init -backend-config="bucket=${TF_S3_BUCKET}" -backend-config="key=${TF_S3_KEY}" -backend-config="region=${AWS_DEFAULT_REGION}"

      - name: Determine K8S-Cluster Terraform Workspace
        working-directory: ./terraform/k8s-cluster
        run: |
          if terraform workspace select ${{ env.TF_K8S_WORKSPACE }} 2>/dev/null; then
            echo "Workspace ${{ env.TF_K8S_WORKSPACE }} Selected!"
          else
            terraform workspace new ${{ env.TF_K8S_WORKSPACE }}
          fi

      - name: Apply New Terraform
        working-directory: ./terraform/k8s-cluster
        run: terraform destroy -var="sshkey=$(echo "${{ secrets.SSHKEY }}" | base64 --decode)" -auto-approve -lock=false
